name: Resuable_dispatch
on: 
  push:
      branches: none
  workflow_dispatch:
jobs:
    workflowA:
      uses: thomaspauls/github_actions/.github/workflows/reuse_call.yaml@main
      with: 
          username : Thomas
      secrets:
          token: ${{secrets.token}}
     
    workflowB:
        uses: thomaspauls/github_actions/.github/workflows/reuse_call.yaml@main
        with: 
            username : Paul
        secrets:
            token: ${{secrets.token}}
    
         
